import type { ReactNode } from "react";
import { Geist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { SanityLive } from "@/sanity/live";
import { BasketProvider } from "@/lib/BaketContextProv";
import Footer from "@/components/footer";

const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className="min-h-screen flex flex-col font-sans antialiased">
          <BasketProvider>
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
          </BasketProvider>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
