import type { ReactNode } from "react";
import { Geist } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";
import { SanityLive } from "@/sanity/live";
import { BasketProvider } from "@/lib/BaketContextProv";
import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist-sans" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <ClerkProvider dynamic>
      {" "}
      <html lang="en">
        <body className={`${geistSans.variable}  antialiased`}>
          <BasketProvider>
            <Header />
            {children}
            <Footer />
          </BasketProvider>
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
